# FROM ubuntu:22.04
FROM python:3.13.0a5-slim-bullseye
# FROM nvcr.io/nvidia/pytorch:23.08-py3


RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git curl

RUN python3 -m pip install --upgrade pip
RUN pip install numpy matplotlib pandas
# RUN pip install open-interpreter==0.1.4
RUN pip install --upgrade open-interpreter

WORKDIR /app