name: Build and Test

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] # figure out windows-latest later

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Open Interpreter
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/OpenInterpreter/open-interpreter/refs/heads/development/installers/new-installer.sh | sh

      - name: Run tests
        shell: bash
        run: |
          interpreter run tests/ -v --color=yes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONUNBUFFERED: "1"